# Generated by Django 4.1.2 on 2022-10-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiar',
            new_name='Familiares',
        ),
    ]
